export function generateChangelogHTML(sections: any[], version: string, date: string, repoName: string, stats: any): string {
  const totalCommits = sections.reduce((sum, s) => sum + s.commits.length, 0);
  const breakingCount = sections.reduce((sum, s) => sum + s.commits.filter((c: any) => c.breaking).length, 0);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Changelog - ${repoName} ${version}</title>
  <style>
    *{margin:0;padding:0;box-sizing:border-box}
    body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f8f9fa;color:#1a1a2e;line-height:1.6;padding:2rem}
    .container{max-width:800px;margin:0 auto}
    header{background:#fff;border-radius:12px;padding:2rem;margin-bottom:2rem;box-shadow:0 1px 3px rgba(0,0,0,.1)}
    h1{font-size:2rem;margin-bottom:.5rem}
    .meta{color:#666;font-size:.9rem;margin-bottom:1rem}
    .stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:1rem;margin-top:1rem}
    .stat{text-align:center;padding:.75rem;background:#f0f4ff;border-radius:8px}
    .stat-value{font-size:1.5rem;font-weight:bold;color:#4361ee}
    .stat-label{font-size:.75rem;color:#666;text-transform:uppercase}
    .section{background:#fff;border-radius:12px;padding:1.5rem;margin-bottom:1rem;box-shadow:0 1px 3px rgba(0,0,0,.1)}
    .section-title{font-size:1.25rem;margin-bottom:1rem;display:flex;align-items:center;gap:.5rem}
    .commit{padding:.5rem 0;border-bottom:1px solid #f0f0f0}
    .commit:last-child{border-bottom:none}
    .commit-scope{background:#e8f4fd;color:#0066cc;padding:.125rem .375rem;border-radius:4px;font-size:.75rem;margin-right:.5rem}
    .commit-breaking{background:#fee;color:#c00;padding:.125rem .375rem;border-radius:4px;font-size:.75rem;margin-right:.5rem;font-weight:600}
    .commit-message{margin-left:.5rem}
    .commit-meta{font-size:.75rem;color:#999;margin-top:.25rem}
    footer{text-align:center;margin-top:2rem;color:#666;font-size:.85rem}
    @media(max-width:600px){body{padding:1rem}.stats{grid-template-columns:repeat(2,1fr)}}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>${repoName} Changelog</h1>
      <div class="meta">Version <strong>${version}</strong> &middot; ${date}</div>
      <div class="stats">
        <div class="stat"><div class="stat-value">${totalCommits}</div><div class="stat-label">Commits</div></div>
        <div class="stat"><div class="stat-value">${sections.length}</div><div class="stat-label">Sections</div></div>
        <div class="stat"><div class="stat-value">${breakingCount}</div><div class="stat-label">Breaking</div></div>
        <div class="stat"><div class="stat-value">${stats.contributors || sections.reduce((s: number, sec: any) => { const a = sec.commits.map((c: any) => c.author); return [...new Set(a)]; }).length}</div><div class="stat-label">Contributors</div></div>
      </div>
    </header>
    ${sections.map((section: any) => `
    <div class="section">
      <h2 class="section-title">${section.icon || '📦'} ${section.label}</h2>
      ${section.commits.map((commit: any) => `
        <div class="commit">
          <span class="commit-meta">${commit.scope ? `<span class="commit-scope">${commit.scope}</span>` : ''}${commit.breaking ? '<span class="commit-breaking">BREAKING</span>' : ''}</span>
          <span class="commit-message">${commit.message}</span>
          <div class="commit-meta">
            <a href="${commit.url || '#'}" style="color:#666;text-decoration:none">${commit.sha?.substring(0, 7) || 'unknown'}</a> by ${commit.author || 'unknown'}
          </div>
        </div>
      `).join('')}
    </div>
    `).join('')}
    <footer>Generated by <a href="https://releaseflow.dev" style="color:#4361ee;text-decoration:none">ReleaseFlow</a></footer>
  </div>
</body>
</html>`;
}

export function generateRSSFeed(sections: any[], version: string, date: string, repoName: string, repoUrl: string): string {
  const totalCommits = sections.reduce((sum, s) => sum + s.commits.length, 0);
  const items = sections.flatMap((section: any) =>
    section.commits.map((commit: any) => `
    <item>
      <title>${section.label}: ${commit.message}</title>
      <link>${repoUrl}/commit/${commit.sha}</link>
      <guid>${commit.sha}</guid>
      <pubDate>${new Date(commit.date).toUTCString()}</pubDate>
      <description>${commit.scope ? `[${commit.scope}] ` : ''}${commit.message}</description>
      <category>${section.type}</category>
      <author>${commit.author}</author>
    </item>`).join('')
  ).join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>${repoName} Changelog</title>
    <link>${repoUrl}</link>
    <description>Changelog for ${repoName}</description>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <language>en-us</language>
    <item>
      <title>Version ${version} Released</title>
      <link>${repoUrl}/releases/tag/${version}</link>
      <guid>${version}</guid>
      <pubDate>${new Date(date).toUTCString()}</pubDate>
      <description>${totalCommits} commits in this release</description>
    </item>
    ${items}
  </channel>
</rss>`;
}

export function generateJSONLD(sections: any[], version: string, date: string, repoName: string): any {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareSourceCode",
    name: repoName,
    codeRepository: `https://github.com/${repoName}`,
    release: {
      "@type": "SoftwareApplication",
      softwareVersion: version.replace(/^v/, ''),
      datePublished: date,
      description: generateChangelogSummary(sections),
      changeLog: sections.map((section: any) => ({
        "@type": "CreativeWork",
        about: section.label,
        text: section.commits.map((c: any) => c.message).join('. '),
      })),
    },
  };
}

export function generateChangelogSummary(sections: any[]): string {
  const summaries: string[] = [];
  for (const section of sections) {
    if (section.type === 'feat') {
      summaries.push(`Added ${section.commits.length} new feature(s)`);
    } else if (section.type === 'fix') {
      summaries.push(`Fixed ${section.commits.length} issue(s)`);
    } else if (section.type === 'perf') {
      summaries.push(`Improved performance in ${section.commits.length} area(s)`);
    } else if (section.type === 'docs') {
      summaries.push(`Updated documentation (${section.commits.length} change(s))`);
    }
    if (section.commits.some((c: any) => c.breaking)) {
      summaries.push('⚠️ Contains breaking changes');
    }
  }
  return summaries.length > 0 ? summaries.join('. ') : 'No significant changes';
}

export function computeChangelogStats(sections: any[]): any {
  const allCommits = sections.flatMap((s: any) => s.commits);
  const authors = new Set(allCommits.map((c: any) => c.author));
  const scopes = new Set(allCommits.filter((c: any) => c.scope).map((c: any) => c.scope));
  const breakingCount = allCommits.filter((c: any) => c.breaking).length;

  const typeCounts: Record<string, number> = {};
  for (const section of sections) {
    typeCounts[section.type] = section.commits.length;
  }

  const scopeGroups: Record<string, number> = {};
  for (const commit of allCommits) {
    if (commit.scope) {
      scopeGroups[commit.scope] = (scopeGroups[commit.scope] || 0) + 1;
    }
  }

  const topScopes = Object.entries(scopeGroups)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([scope, count]) => ({ scope, count }));

  return {
    totalCommits: allCommits.length,
    contributors: authors.size,
    scopes: scopes.size,
    breakingChanges: breakingCount,
    typeCounts,
    topScopes,
    sectionsCount: sections.length,
  };
}

export function generateSlackBlocks(sections: any[], version: string, repoName: string): any[] {
  const blocks: any[] = [
    {
      type: 'header',
      text: { type: 'plain_text', text: `🚀 ${repoName} ${version}`, emoji: true },
    },
    {
      type: 'divider',
    },
  ];

  for (const section of sections) {
    if (section.commits.length === 0) continue;

    const commitText = section.commits
      .map((c: any) => `${c.scope ? `*${c.scope}:* ` : ''}${c.message}${c.breaking ? ' ⚠️' : ''}`)
      .join('\n');

    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*${section.icon || '📦'} ${section.label}*\n${commitText}`,
      },
    });
    blocks.push({ type: 'divider' });
  }

  blocks.push({
    type: 'context',
    elements: [
      {
        type: 'mrkdwn',
        text: `Generated by *ReleaseFlow* | ${new Date().toISOString().split('T')[0]}`,
      },
    ],
  });

  return blocks;
}

export function generateDiscordEmbed(sections: any[], version: string, repoName: string, color: number = 0x4361ee): any {
  const fields = sections
    .filter((s) => s.commits.length > 0)
    .map((section) => ({
      name: `${section.icon || '📦'} ${section.label}`,
      value: section.commits
        .map((c: any) => `${c.scope ? `**${c.scope}:** ` : ''}${c.message}${c.breaking ? ' ⚠️' : ''}`)
        .join('\n'),
      inline: false,
    }));

  return {
    title: `🚀 ${repoName} ${version}`,
    description: 'New release is here!',
    color,
    fields,
    footer: {
      text: `Generated by ReleaseFlow • ${new Date().toISOString().split('T')[0]}`,
    },
    timestamp: new Date().toISOString(),
  };
}
