import { Metadata } from "next";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  
  const lastDashIndex = slug.lastIndexOf("-");
  const repoIdentifier = slug.substring(0, lastDashIndex);
  const repoName = repoIdentifier.split("/").pop() || repoIdentifier || "repo";

  return {
    title: `${repoName} Changelog | ReleaseFlow`,
    description: `Release notes and updates for ${repoName} generated by ReleaseFlow`,
    openGraph: {
      title: `${repoName} Changelog`,
      description: "Release notes and updates",
      type: "website",
    },
    other: {
      "script:ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "SoftwareSourceCode",
        name: repoName,
        provider: {
          "@type": "Organization",
          name: "ReleaseFlow",
        },
      }),
    },
  };
}