"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeftIcon, MailIcon, CopyIcon, CheckIcon, SendIcon } from "@/components/ui/icons";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";

export default function EmailDigestPage() {
  const [copied, setCopied] = useState(false);
  const [template, setTemplate] = useState("weekly");

  const generateEmailTemplate = () => {
    const templates = {
      weekly: `Subject: 📦 Weekly Release Digest - [REPO_NAME]

Hey team! 👋

Here's what shipping this week:

🚀 Features
• New user dashboard with analytics
• Dark mode support
• Improved search

🐛 Bug Fixes
• Login redirect issue fixed
• Mobile responsiveness improved

⚡ Performance  
• Database query optimization

━━━━━━━━━━━━━━━━━━━━━━━━
Total: 12 changes from 3 contributors

🚀 Your Friends at [TEAM_NAME]
Generated by ReleaseFlow`,

      monthly: `Subject: 📊 Monthly Release Summary - [MONTH]

Hi everyone! 

Here's the monthly digest:

📈 Stats
• 45 features shipped
• 23 bug fixes
• 12 contributors

🏆 Top Contributors
• @developer1 - 15 commits
• @developer2 - 12 commits  
• @developer3 - 8 commits

🔜 Coming Soon
• New API endpoints
• Mobile app launch

Thank you for making this possible! 🙏

Best,
[TEAM_NAME]`,

      release: `Subject: 🎉 New Release v[X.X.X] Available

Hello! 

We're excited to announce version v[X.X.X] is now live! 

📝 What's New
• [Feature 1]
• [Feature 2]
• [Feature 3]

🐛 Fixed  
• [Bug fix 1]
• [Bug fix 2]

🔧 Breaking Changes
• [If any]

📦 Upgrade: npm install [package]@latest

Questions? Reply to this email!

— The Release Team`,
    };

    return templates[template as keyof typeof templates];
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generateEmailTemplate());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="flex items-center gap-4 mb-8">
          <Link href="/dashboard" className="p-2 rounded-lg hover:bg-gray-100">
            <ArrowLeftIcon className="w-5 h-5 text-gray-600" />
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Email Digest</h1>
            <p className="text-gray-600">Weekly/monthly release email templates</p>
          </div>
        </div>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Email Template</CardTitle>
            <CardDescription>Select and customize your email template</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex gap-2">
              {(["weekly", "monthly", "release"] as const).map((t) => (
                <Button
                  key={t}
                  variant={template === t ? "default" : "outline"}
                  size="sm"
                  onClick={() => setTemplate(t)}
                >
                  {t.charAt(0).toUpperCase() + t.slice(1)}
                </Button>
              ))}
            </div>

            <div className="bg-gray-900 text-gray-100 p-6 rounded-lg font-mono text-sm whitespace-pre-wrap">
              {generateEmailTemplate()}
            </div>

            <Button onClick={handleCopy}>
              {copied ? <CheckIcon className="w-4 h-4 mr-2" /> : <CopyIcon className="w-4 h-4 mr-2" />}
              {copied ? "Copied!" : "Copy Template"}
            </Button>
          </CardContent>
        </Card>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Variables</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
              {["REPO_NAME", "TEAM_NAME", "MONTH", "VERSION", "CONTRIBUTORS", "TOTAL_CHANGES", "TOP_CONTRIBUTOR", "DATE"].map((v) => (
                <div key={v} className="flex items-center gap-2 p-2 bg-gray-50 rounded text-sm font-mono">
                  <span className="text-blue-500">[{v}]</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Integration</CardTitle>
            <CardDescription>Connect with email services</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <button className="w-full flex items-center gap-3 p-3 border rounded-lg hover:bg-gray-50">
              <img src="https://logo.clearbit.com/sendgrid.com" className="w-6 h-6" alt="SendGrid" />
              <span>SendGrid</span>
            </button>
            <button className="w-full flex items-center gap-3 p-3 border rounded-lg hover:bg-gray-50">
              <img src="https://logo.clearbit.com/mailgun.org" className="w-6 h-6" alt="Mailgun" />
              <span>Mailgun</span>
            </button>
            <button className="w-full flex items-center gap-3 p-3 border rounded-lg hover:bg-gray-50">
              <img src="https://logo.clearbit.com/resend.dev" className="w-6 h-6" alt="Resend" />
              <span>Resend</span>
            </button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}