import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { repoOwner, repoName, prTitle, prBody, baseBranch = "main" } = body;

    if (!repoOwner || !repoName || !prTitle) {
      return NextResponse.json(
        { error: "repoOwner, repoName ve prTitle gerekli" },
        { status: 400 }
      );
    }

    const token = request.headers.get("x-github-token");
    if (!token) {
      return NextResponse.json(
        { error: "GitHub token gerekli" },
        { status: 401 }
      );
    }

    // PR template oluştur
    const template = `## Description
${prBody || "Please include a summary of the changes and any relevant context."}

## Type of Change
- [ ] 🚀 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation
- [ ] 💄 Styles
- [ ] ♻️ Refactoring
- [ ] ⚡ Performance
- [ ] ✅ Tests
- [ ] 📦 Build System
- [ ] 🔧 CI/CD

## Breaking Changes
- [ ] Yes
- [ ] No

## Checklist
- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added documentation (if applicable)

## Related Issues
Closes #(issue number)

## Screenshots (if applicable)
Add screenshots here.

---
Generated by [ReleaseFlow](https://releaseflow.dev)`;

    // GitHub API ile PR oluştur (opsiyonel)
    if (request.headers.get("create-pr") === "true") {
      const response = await fetch(
        `https://api.github.com/repos/${repoOwner}/${repoName}/pulls`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${token}`,
            Accept: "application/vnd.github.v3+json",
          },
          body: JSON.stringify({
            title: prTitle,
            body: template,
            base: baseBranch,
            head: "main", // Kullanıcı tarafından belirlenecek
          }),
        }
      );

      if (!response.ok) {
        const error = await response.json().catch(() => ({}));
        return NextResponse.json(
          { error: `PR oluşturulamadı: ${error.message || response.statusText}` },
          { status: response.status }
        );
      }

      const data = await response.json();
      return NextResponse.json({
        success: true,
        prUrl: data.html_url,
        template,
        message: "PR oluşturuldu",
      });
    }

    return NextResponse.json({
      success: true,
      template,
      message: "PR template oluşturuldu",
    });
  } catch (error) {
    console.error("PR template error:", error);
    return NextResponse.json(
      { error: "PR template oluşturulamadı" },
      { status: 500 }
    );
  }
}
